name: "Solax X3 RS485"
description: "Solax PowerScraper wrapper"
version: "1.0.33"
slug: "solax_power_scraper"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  34800/tcp: 34800
uart: true
services:
  - "mqtt:need"
options:
  serial: "/dev/ttyUSB0"
  port: 34800
  mqtt:
    topic: "solax"
schema:
  serial: device(subsystem=tty)
  port: port
  mqtt:
    topic: str
webui: http://[HOST]:[PORT:34800]
