name: "Solax X3 RS485"
description: "Solax PowerScraper wrapper"
version: "1.0.110"
slug: "solax_power_scraper"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
uart: true
services:
  - "mqtt:need"
options:
  serial: "/dev/ttyUSB0"
  device:
    identifiers: "MCXXXXXXXXXXXX"
    name: SolaxX3
    sw_version: "1.0"
    model: X3-MIC/PRO
    manufacturer: Solax
  debug: false
schema:
  serial: device(subsystem=tty)
  device:
    identifiers: str
    name: str
    sw_version: str
    model: str
    manufacturer: str
  debug: bool
